brevia-ai/brevia

- .env.sample
- brevia/language.py
- brevia/prompts/qa/default.system.yaml
- brevia/query.py
- brevia/routers/qa_router.py
- pyproject.toml
This PR introduces some Q/A default behaviors that can be stored in `collections` metadata.
In `cmetadata` JSON field of a collection you can now store:
* `chat_lang` language to use to answer questions in Q/A flow
* `docs_num` default number of documents used in search and Q/A (`SEARCH_NUM_DOCS` env var used as fallback)
* `model_name` model to use in Q/A flow (`QA_MODEL` env var used as fallback)
* `temperature` temperature parameter to use (`QA_TEMPERATURE` env var used as fallback)
`chat_lang` can now be passed in `/prompt` endpoint and takes precedence over the collection parameter
Changes in environment variables:
* `FEATURE_QA_LANG_DETECT` (default False) is used to enable language detection of question in Q/A flow using `Spacy`, if this variable is not set automatic language …
> Handle Q/A defaults in collection metadata

- brevia/routers/analyze_router.py
- brevia/services.py
- tests/routers/test_analyze_router.py
This PR adds an optional `payload` argument to `/upload_summary` endpoint.
This provides custom options and custom fields to add in the async job service.
> Add optional `payload` in `/upload_summary`

- brevia/chat_history.py
- brevia/routers/chat_history_router.py
- tests/test_chat_history.py
This PR adds a session_id filter to be used in `GET /chat_history` endpoint along with existing filters.
Example:
```
GET  /chat_history?session_id={uuid}&collection={collection}&min_date=2023-12-07
````
Retrieve a specific session on a collection starting from a date
> Add `session_id` filter to chat history

- brevia/postman/Brevia API.postman_collection.json
- brevia/postman/Brevia API.postman_environment.json
- brevia/query.py
- brevia/routers/qa_router.py
- tests/routers/test_qa_router.py
- tests/test_query.py
This PR adds support for metadata filters in both `/search` and `/chat` endpoints.
It is now possible to introduce filters like these: 
```http
POST /search
{
"query": "my query...",
"collection": "my-collection",
"filter": {"category": "my-category"} 
}
```
```http
POST /chat
{
"question": "my question is: ...",
"collection": "my-collection",
"filter": {"category": {"in": ["first", "second"]}} 
}
```
There are two filter type available: you can combine metadata filter by using specific keys and values or by using `IN` conditions with a dictionary object like in the second examples.
Other changes:
* new `SearchQuery` and `ChatParams` pydantic models have been added to handle common fields in search and chat use cases
* unit and integration tests have been added to `query` and …
> Add metadata filter in `/search` and `/chat`

- brevia/settings.py
- tests/conftest.py
- tests/test_models.py
This PR fixes a problem with test settings: values in `tests/.env` file were not overriding ones in `Settings` instance as expected in unit tests
> Fix tests settings

- brevia/async_jobs.py
- brevia/chat_history.py
- brevia/collections.py
- brevia/connection.py
- brevia/dependencies.py
- brevia/index.py
- brevia/query.py
- brevia/routers/index_router.py
- poetry.lock
- pyproject.toml
- tests/test_query.py
This PR updates `langchain` to the latest version, introducing new metadata filter operators like IN, GT, LT... 
see https://github.com/langchain-ai/langchain/pull/14852
A couple of simple test cases with operators have been added to `test_query::test_search_vector_filter()`
> Upgrade langchain - new metadata filter operators

- brevia/index.py
- brevia/routers/index_router.py
- tests/routers/test_index_router.py
This PR introduces a new endpoint to update metadata of a single documenta in a collection.
Example usage:
```http
POST /index/metadata
{
"collection_id": "{uuid}",
"document_id": "{doc_id}",
"metadata": {"category": "second"},
}
```
Where `{uuid}` and `{doc_id}` are the requested collection and document id.
> Update document index metadata endpoint

- brevia/callback.py
- brevia/routers/qa_router.py
This PR fixes a problem with token usage callback that generate an error when saving chat history items.
* a new `token_usage` function has been added to extract usage data
* `token_usage_callback` and `TokensCallbackHandler` aliases for future uses, only OpenAI token count is supported for now
> Fix token usage callback error

- brevia/alembic/versions/b34017752e45_chat_history_evaluation.py
- brevia/chat_history.py
- brevia/postman/Brevia API.postman_collection.json
- brevia/postman/Brevia API.postman_environment.json
- brevia/routers/chat_history_router.py
- brevia/routers/collections_router.py
- tests/routers/test_chat_history_router.py
In this PR a new `/evaluate` endpoint has been introduced to allow a user to evaluate a chat reponse
Usage example: 
```http
POST /evaluate
{
"uuid": "{{chat_history_id}}",
"user_evaluation": false,
"user_feedback": "Chat answer is incomprehensible",
}
```
where `{{chat_history_id}}` is the chat history record uuid.
Main changes:
* a new alembic migration to add evaluation related fields to `chat_history` table
* `/evaluate` endpoint and new `history_evaluation` function in `chat_history` module
* evaluation fields added in `GET /chat_history` response
* postman reference files updated
> Chat response user evaluation endpoint - `/evaluate`

- brevia/completions.py
This PR fixes a problem with `qa_completion_llm` setting in `POST /completions` API calls.
We must use a copy of `qa_completion_llm` in `load_chatmodel()` method to avoid setting change and errors on next API calls
> Fix `qa_completion_llm` configuration usage in `/completions` endpoint

- brevia/chat_history.py
- tests/test_chat_history.py
This PR solves a problem using `max_date` and `min_date` query string filters in `/chat_history` 
End of day timestamp is used for `max_date` and start of day timestamp in `min_date` to include all expected history items-
> Use end of day and start of day in history filter

- brevia/callback.py
- brevia/routers/qa_router.py
- tests/test_callback.py
This PR adds `chat_history_id` of the last `question`/`answer` in a chat action to be used for a user evaluation (via `POST /evaluation`)
* in case of streaming chat an item with `chat_history_id` is appended in streaming response content 
* if no streaming is requested a new `chat_history_id` field will appear in chat response
> Add chat history id in `/chat` response

- brevia/routers/index_router.py
This PR introduces file loader options in `POST /index/upload` API call 
This way we can handle some options like OCR in scanned pdfs and similar use cases where additional parameters/information is needed to extract textual information.
> Add file loader options in `POST /index/upload`

- brevia/chat_history.py
- brevia/collections.py
- brevia/index.py
- brevia/postman/Brevia API.postman_collection.json
- brevia/routers/index_router.py
- brevia/utilities/json_api.py
- brevia/utilities/uuid.py
- tests/routers/test_index_router.py
This PR introduces two new collection index endpoints:
* `GET /index/{collection_id}`: returns a paginated list of documents indexed in a collection; each item corresponds to a `pg_embeddings` record, so you can get usually more items for the same document 
* `GET /index/{collection_id}/documents_metadata`: returns a list of documents metadata in a collection, so you will get unique items with `cmetadata` and `custom_id` (alias for document id in brevia) 
* both endpoints come with a `filter` query string on metadata to allow filters on specific metadata keys and values 
Example:
```http
GET /index/{collection_id}?filter[type]=questions
```
Will return all items having `"type": "questions"` key/value in `cmetadata` 
```http
GET /index/{collection_id}/index_metadata?filter[type]=files&filte …
```
> New `/index/{id}` and `/index/{id}/documents_metadata` endpoints

- brevia/load_file.py
- brevia/postman/Brevia API.postman_collection.json
- brevia/postman/Brevia API.postman_environment.json
- brevia/routers/index_router.py
- tests/routers/test_index_router.py
This PR introduces a new endpoint - `POST /index/link` to index a web page in a collection providing the web page link
New endpoint signature example:
```http
POST /index/link
{
"link": "https:/www.example.com/my-page",
"collection_id": "############",
"document_id": "123",
"metadata": {"type": "links", "category": "one"},
"options": {"selector": ".content"}
}
```
Where in the optional `options` field you may provide some rules to filter the HTML page. In this case tags within a `content` class will be extracted. 
A new `load_file.read_html_url` method has been added to HTML load file content from a remote URL and provide optional filters with selector rules
> New `/index/link` endpoint: index web page via link

- brevia/index.py
- brevia/routers/index_router.py
- tests/routers/test_index_router.py
This PR adds a `document_id` query string to get metadata of a single document
> Add `document_id` query string to `/index/{{collection_id}}/documents_metadata` endpoint

- brevia/commands.py
- brevia/index.py
- brevia/load_file.py
- pyproject.toml
- tests/routers/test_index_router.py
- tests/test_commands.py
- tests/test_index.py
This PR introduces a new `update_collection_links` command do the following:
* find documents for a collection having `type`:`files` and a populated `url` in metadata 
* check current `url` text content and compare it with the corresponding text stored 
* if the url text content has changed replaced the indexed content with the new one
A new ordering `part` metadata key (from 1 to N) has been introduced to be able to restore the original content in the correct order.
> New `update_collection_links` command

- brevia/alembic/versions/95d93297832c_migration_to_jsonb_format.py
- brevia/index.py
- brevia/query.py
- tests/routers/test_qa_router.py
- tests/test_query.py
Use the more efficient and fast `JSONB` type for `cmetadata` column in embeddings table, instead of `JSON`
> Migrate metadata column to JSONB

- brevia/load_file.py
- tests/routers/test_index_router.py
This PR adds an optional callback that can be used when loading a web page link in a collection.
Example
```http
POST /index/link
{
"link": "https://www.example.com",
"collection_id": "{uuid}",
"document_id": "123",
"metadata": {"type": "links"},
"options": {"callback": "my_module.my_function"}
}
```
`my_module.my_function` will be imported and called upon the HTML content before saving the extracted text in the `{uuid}` collection.
> Callback when loading web links

- brevia/index.py
- brevia/load_file.py
- brevia/utilities/files_import.py
- tests/test_load_file.py
in this PR:
* same documents splitting logic is used in `import_file` command as in `POST /index/*` endpoints 
* collection metadata are now handled correctly:
- `collection.cmetadata` may be `NULL` 
- `chunk_size/overlap` params are now converted to `int`
> Fix `import_file` command and collection metadata in indexing

- docker-compose.yml
This PR fixes the docker compose to use default value for BREVIA_ENV_SECRETS.
> Set default value for BREVIA_ENV_SECRETS in docker compose

- brevia/index.py
- brevia/routers/app_routers.py
- tests/conftest.py
This PR introduces a minor refactor in `index` module: `init_index` has been deprecated and replaced by `init_splitting_data`
The new method will not be called at API startup but on the first indexing operation inside `split_document()` just once using `@lru_cache` annotation
> Refactor: use `init_splitting_data` with cache annotation

- brevia/middleware.py
- main.py
- poetry.lock
- pyproject.toml
- tests/test_middleware.py
In this PR a new `VersionHeaderMiddleware` has been added to add custom response headers containing Brevia version and optionally of the custom API that's using Brevia.
* a new `X-Brevia-Version` header will be always emtted containing Brevia version in use 
* two optional header `X-Api-Version` and `X-Api-Name` can be emitted if middleware is configured this way in your `main.py`
```python
from pathlib import Path
from fastapi import FastAPI
from brevia.middleware import VersionHeaderMiddleware
from brevia.utilities.openapi import metadata
meta = metadata(f'{Path(__file__).parent}/pyproject.toml')
app = FastAPI(**meta)
app.add_middleware(VersionHeaderMiddleware, api_name=app.name, api_version=app.version)
```
Using this code name and version of your API defined in `pyproject.toml` will …
> Add version in header response via middleware

- .gitignore
- brevia/prompts/text_analysis/questions_initial.yml
- brevia/prompts/text_analysis/questions_refine.yml
- brevia/services.py
- brevia/settings.py
- brevia/tasks/base.py
- brevia/tasks/text_analysis.py
- tests/conftest.py
- tests/files/prompts/initial_prompt.yml
- tests/files/prompts/refine_prompt.yml
- tests/tasks/test_text_analysys.py
- tests/test_services.py
In this PR:
* a new `RefineTextAnalysisTask` and its abstract parent `BaseAnalysisTask` have been introduced to perform simple tasks with custom provided prompts using a `refine` algorithm provided by LangChain `RefineDocumentsChain` (that will be migrated to new LCEL format soon)
* a new `RefineTextAnalysisService` has also been added to implement this task in an async job.
* a new `prompts_base_path` setting  has been added with `./prompts` as default, relative to the current working dir, to define a base file path or URL to store and load prompts by name
> Introduce `refine` text analysis task and service

- brevia/index.py
- brevia/routers/index_router.py
- tests/routers/test_index_router.py
- tests/test_index.py
This PR will enable any option to be used in `link_load_options` configuration. 
This options will be used in `POST /index/link` if no option are set in the request body, by looking at collection metadata.
As of today only `selector` option was selected. 
Internally `selector` and `callback` are used, but this change allows the introduction of other options in the future.
> Handle any option in `link_load_options` metadata setting

- alembic.ini
- brevia/alembic/__init__.py
- tests/conftest.py
This PR fixes a problem with alembic `script_location` configuration when using migrations commands using `brevia` package
`script_location` points to the folder containing alembic scripts: using `alembic.ini` in a project using `brevia` you may not know the correct path in advance. This happens, for instance, if your Brevia project supports multiple Python versions.
From now on this path will be set at runtime.
> Set alembic `script_location` config at runtime

- .env.sample
- brevia/postman/Brevia API.postman_collection.json
- brevia/providers.py
- brevia/routers/config_router.py
- brevia/routers/providers_router.py
- brevia/settings.py
- docs/config.md
- docs/endpoints_overview.md
- tests/routers/test_config_router.py
- tests/routers/test_providers_router.py
- tests/test_providers.py
- tests/test_settings.py
In this PR:
* a new `GET /providers/{provider}` endpoint has been added to retrieve available models of a single providers 
* a boolean `list_models` query parameter, with default value `true`, has been added to optionally list providers without models in `GET /providers` 
* a multiple `key` query parameter in `GET /config` endpoint has been introduced to list only specific configuration keys 
* a new `providers_env_vars` was added. to list of known environment variables for every provider 
* some changes to `brevia_env_secrets` have been introduced:
- if an environment variablie listed in `providers_env_vars` has been set it will be added to `brevia_env_secrets` if not there already 
- if an item is removed from `brevia_env_secrets`, its corresponding variable is also removed from the …
> Update `brevia_env_secrets` usage + new `GET  /providers/{provider}` endpoint + new `providers_env_vars` setting

- brevia/settings.py
This PR updates the settings module to use a module relative path for locating prompt files rather than relying on the current working directory, otherwise we get `FileNotFoundError` using `brevia` library without setting a prompts base path.
> Use module relative path for default file prompts
